version: '2'
services:
  application:
    image: pubsub
    build:
      context: ../application
    environment:
      - PUBSUB_EMULATOR_HOST="emulator:8085"
      - PUBSUB_PROJECT_ID="my-project-id"
    depends_on:
      - emulator
  database:
    image: pubsub
    build:
      context: ../application
    environment:
      - PUBSUB_EMULATOR_HOST="emulator:8085"
      - PUBSUB_PROJECT_ID="my-project-id"
    depends_on:
      - emulator
  emulator:
    image: adilsoncarvalho/gcloud-pubsub-emulator
    ports:
      - "8085:8085"